# Master config
defaults:
  - dataset: wayve101
  #  --- Models ---
  - model@segmenter: sam3       # Loads model/sam3.yaml into cfg.segmenter
  - model@diffusion: difix3d+      # Loads model/difix3d+.yaml into cfg.diffusion
  - model@tracker: cc3dt        # Loads model/cc3dt.yaml into cfg.tracker

  # --- Pipeline Tasks ---
  - pipeline@seg_task: extract_masks      # Loads pipeline/extract_masks.yaml into cfg.seg_task
  - pipeline@diff_task: apply_diffusion   # Loads pipeline/apply_diffusion.yaml into cfg.diff_task
  - pipeline@pseudo_task: difix_pseudo    # Loads pipeline/difix_pseudo.yaml into cfg.pseudo_task
  - pipeline@loop_task: difix_loop        # Loads pipeline/difix_loop.yaml into cfg.loop_task
  - pipeline@track_task: run_tracking     # Loads pipeline/run_tracking.yaml into cfg.track_task
  - pipeline@refine_task: refine_tracks   # Loads pipeline/refine_tracks.yaml into cfg.refine_task

  - gaussian_splatting: train
  - rendering@rendering: render   # Loads rendering/render.yaml into cfg.rendering
  - rendering@simulator: simulator # Loads rendering/simulator.yaml into cfg.simulator
  - _self_

scene_name: "${dataset.scene}"
# Global fallback variables
exp_name: "manual_debug_run"

hydra:
  run:
    # Fallback directory if running scripts manually outside the orchestrator
    dir: results/manual_runs/${dataset.name}/${scene_name}/${exp_name}_${now:%m%d_%H%M}

mask_processing:
  use_ego_masks: true
  dilate_ego: false
  dilation_percentage: 0.15
