# Master config
defaults:
  - dataset: wayve101
  #  --- Models ---
  - model@segmenter: sam3       # Loads model/sam3.yaml into cfg.segmenter
  - model@diffusion: difix3d+      # Loads model/difix3d+.yaml into cfg.diffusion

  # --- Pipeline Tasks ---
  - pipeline@seg_task: extract_masks      # Loads pipeline/extract_masks.yaml into cfg.seg_task
  - pipeline@diff_task: apply_diffusion   # Loads pipeline/apply_diffusion.yaml into cfg.diff_task

  - gaussian_splatting: train
  - _self_

scene_name: "${dataset.scene}"
# Global fallback variables
exp_name: "manual_debug_run"

hydra:
  run:
    # Fallback directory if running scripts manually outside the orchestrator
    dir: results/manual_runs/${dataset.name}/${scene_name}/${exp_name}_${now:%m%d_%H%M}

mask_processing:
  dilation_percentage: 0.2
  dilate_ego: false
